// src/data.js
export const blogPosts = [
    {
      id: 1,
      title: 'Blog Post 1',
      content: 'Thoughts on the revision videos: As always revision is a vital aspect in not only understanding concepts, we have been taught but also in helping us remember the main points and theories we have learnt. The revision videos were helpful in jogging my memory of what certain concepts meant as well as how to implement them. This was especially important when it came to coding. The revision videos allowed me the opportunity to recall what certain code did and how it worked as well as the value it could add to future assignments. Art on its own is highly intriguing so adding the internet into the mix makes it rather special. This avenue of art really showcases the many little branches that exist within the concept of art itself. Internet art is interesting because it uses the internet as its main platform or medium. The reason I find this form of art intriguing is because it encompasses a wide range of creative and artistic practices and expressions that are designed with the sole purpose of existing on the web. It makes use of the many available characteristics and technologies of the web like coding languages to build beautiful works. One internet artwork that instantly grabbed my attention was one that was part of the electronic literature collection. I do not remember the name of it but the main theme behind it was being stalked. The reason it caught my attention is because of the chilling feeling it brought about upon me despite me being aware that it was just an experience. The theme may be one of horror but the feelings it evoked and experience it gave me are so memorable because of how dark it was. My thoughts on the readings: Both readings that I did on internet art were quite insightful. The reading that I want to focus on though is the ‘McNamara - 2020 - RIP Adobe Flash Five Takeaways About the Plug-in’ one. It was a really interesting reading in that it spoke about the great wonder that Adobe Flash was and how significant it was in the realm of internet art while contrasting it to the fact that once social media and media-friendly standards started to rise and gain popularity, Adobe Flash started to decline meaning that all the wonderful works created on it would disappear with it. The reason this contrast stood out to me was because the reading went from praising how influential and potentially life changing Adobe Flash was in relation to internet art to how fragile it became once other things like social media started gaining traction.',
      preview: 'As always revision is a vital aspect in not only...',
    },
    {
      id: 2,
      title: 'Blog Post 2',
      content: 'Thoughts on the revision videos: The revision video on the worldwide web this week was a refreshing recap of the content I learnt about this same topic last year. It reminded me of the concept of interactivity in relation to the web and how once something is added to a computer it instantly becomes interactive according to Manovich. This topic of discussion also got me thinking about interactivity within my own works like the websites I have created and how interactivity of elements within the website are what make it intriguing to the users.       My brainstorming and ideas for my single page application:      At this point in time, I have not thought much about how I am going to create my single page application and what the layouts of each page are going to look like however, the theme that I am certainly going to use for this application is Formula 1, specifically the Scuderia Ferrari team. It is a main interest for me in my life outside of university and is something I look forward to watching every weekend. The reason I chose this theme to centre my application around is because it is an exciting interest of mine which means all the research that needs to be done on it will be an enjoyable experience as well as a great opportunity for me to learn more about this high-end sport and where it all began. I also believe that it will make the process of creating something new less daunting.          I have started looking at other Formula 1 websites and car websites to see if there are major similarities that make a good car website and if I can implement any of those ideas into my own application. All the layouts seem to encompass the nature of the car or the sport thereby showcasing what each one is about. This is an element that I would like my single page application to contain. I want it to convey the very essence of Formula 1 and Scuderia Ferrari. This will be a solid way to create a relationship between the theme and the application itself.',
      preview: 'The revision video on the worldwide web this week...',
    },
    {
      id: 3,
      title: 'Blog Post 3',
      content: 'Thoughts on my progress and development using React:     React has been a fun learning experience for me. Last year, I struggled with grasping the concepts of JavaScript and so I thought that I would be facing a similar situation this year with react. However, the challenges of learning complex nature of JavaScript last year undeniably helped in understanding and grasping the concepts of react. There are moments where I still get a bit confused or I run into an error that I am not entirely sure how to fix, but there are also moments where I get things to work and make interesting work like a weather display or a to-do list that are interactive. I will say that the weekly exercises where I had to use react in different ways each time significantly increased my knowledge and understanding in it. Therefore, when I began creating my site most of the elements I wanted to include in it, I knew how to code it and implement it in a way that was user-friendly. My ideas/inspirations for my internet artwork:      Whilst doing my research on what could be internet artwork, I saw that almost anything created with the internet or can only be used with the net could be considered internet art. Games were also a part of that list. I am thinking about creating a game that involves an F1 car specifically the Ferrari because it will be an exciting way to bring the theme of my site into the internet art as well. Including a game in my site will also be a good way to keep users entertained and engaged with my site well conveying the thrill that Formula 1 is as a sport. The game that I want to create is a very simple one, in that it takes inspiration from a F1 pit stop. Users would have to click the tires of the Ferrari in the correct order as quickly as possible so that they can achieve the fastest time. This game would also add the element of adrenaline that plays a huge role in Formula 1. The other idea that I have thought about takes inspiration from the Red bull website. It is a 3D model of an F1 car that users can interact with by clicking the arrows to get a 360-degree view of the car as well click on certain parts of the car that brings up information about that specific part. However, I am leaning more towards the game.',
      preview: 'React has been a fun learning experience for me...',
    }
  ];
  

  /*This file just contains the data that goes within the blog posts */